//3
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("5.0.003.0919")]
[assembly: AssemblyFileVersion("5.0.003.0919")]

