//28
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("5.0.028.1124")]
[assembly: AssemblyFileVersion("5.0.028.1124")]

