//9
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("5.0.009.1008")]
[assembly: AssemblyFileVersion("5.0.009.1008")]

